version: "3.8"

services:
  postgres_demo:
    image: 'postgres:16.0'
    container_name: postgres_demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rgx#*!32sFcMoG@Q
      POSTGRES_DB: demo-project
    volumes:
      - postgres_data:/var/lib/postgresql/data

  demo-project:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres_demo
    environment:
      POSTGRES_JDBC: jdbc:postgresql://postgres_demo:5432/demo-project

volumes:
  postgres_data: