version: "3.8"

services:
  postgres:
    image: 'postgres:16.0'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: demo-project
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: